## Assignment 

In [76]:
import numpy as np
from PIL import Image
import os

In [77]:
rootDir = '.'
for dirName, subDirList,fileList in os.walk(rootDir):
    print("Found directory : %s" %dirName)

Found directory : .
Found directory : .\.ipynb_checkpoints
Found directory : .\Images


In [73]:
image_array = np.zeros([512,512,3])
print (image_array.ndim)
image_size = (512, 512)

3


In [78]:
for fname in fileList:
    if fname.endswith('.jpg'):
        print(fname)
        img = Image.open(fname)
        print(img)
        resized_img = img.resize((image_size),Image.BICUBIC)
        print(resized_img)
        image_array = np.append(image_array,resized_img)
        #image_array.concatenate(resized_img)
        print(image_array)
        

IM_1.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x2D8B4C22A90>
<PIL.Image.Image image mode=RGB size=512x512 at 0x2D8B4BF8128>
[  0.   0.   0. ... 190. 163. 143.]
IM_10.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x2D8B4C22F98>
<PIL.Image.Image image mode=RGB size=512x512 at 0x2D8B4B081D0>
[  0.   0.   0. ... 183.  64.  39.]
IM_11.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x2D8B4B0F518>
<PIL.Image.Image image mode=RGB size=512x512 at 0x2D8B4C22F98>
[  0.   0.   0. ... 122. 118.  62.]
IM_12.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x2D8B4BF8128>
<PIL.Image.Image image mode=RGB size=512x512 at 0x2D8B4B081D0>
[ 0.  0.  0. ...  3. 36. 64.]
IM_13.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1440x2560 at 0x2D8B4C22C18>
<PIL.Image.Image image mode=RGB size=512x512 at 0x2D8B4C282E8>
[  0.   0.   0. ... 138. 117.  46.]
IM_14.jpg
<PIL.JpegImagePlugin.JpegImageFile im